repo:
  - changed-files:
    - any-glob-to-any-file: '*'

docker:
  - changed-files:
    - any-glob-to-any-file:
        - 'src/**/*'
        - 'compose.yml'
        - 'flake.nix'
        - 'flake.lock'
